# read more https://github.com/yoheimuta/protolint

# Lint directives.
lint:
  # Linter directories to walk.
  directories:
    # The specific directories to exclude.
    exclude:
      # NOTE: UNIX paths will be properly accepted by both UNIX and Windows.
      - api

  # Linter rules.
  # Run `protolint list` to see all available rules.
  rules:
    # Determines whether or not to include the default set of linters.
    no_default: true

    # Set the default to all linters. This option works the other way around as no_default does.
    # If you want to enable this option, delete the comment out below and no_default.
    # all_default: true

    # The specific linters to add.
    add:
      - ORDER
      - INDENT
      - IMPORTS_SORTED
      - MAX_LINE_LENGTH
      - SYNTAX_CONSISTENT
      - PROTO3_GROUPS_AVOID
      - PROTO3_FIELDS_AVOID_REQUIRED
      - PACKAGE_NAME_LOWER_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_END_WITH
      - RPC_NAMES_UPPER_CAMEL_CASE
      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - REPEATED_FIELD_NAMES_PLURALIZED
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_PREFIX
      # Comments
      - MESSAGES_HAVE_COMMENT
      - SERVICES_HAVE_COMMENT
      - RPCS_HAVE_COMMENT
      - ENUMS_HAVE_COMMENT
      - ENUM_FIELDS_HAVE_COMMENT

    # The specific linters to remove.
    remove:
      - FIELDS_HAVE_COMMENT
      - FILE_NAMES_LOWER_SNAKE_CASE

  # Linter rules option.
  rules_option:
    # MAX_LINE_LENGTH rule option.
    max_line_length:
      # Enforces a maximum line length
      max_chars: 120
      # Specifies the character count for tab characters
      tab_chars: 2

    # INDENT rule option.
    indent:
      # Available styles are 4(4-spaces), 2(2-spaces) or tab.
      style: 2
      # Available newlines are "\n", "\r", or "\r\n".
      newline: "\n"
      # Specifies if it should stop considering and inserting new lines at the appropriate positions
      # when the inner elements are on the same line. Default is false.
      not_insert_newline: true

    # IMPORTS_SORTED rule option.
    imports_sorted:
      # Available newlines are "\n", "\r", or "\r\n".
      newline: "\n"

    # ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH rule option.
    enum_field_names_zero_value_end_with:
      suffix: INVALID

    # SERVICE_NAMES_END_WITH rule option.
    service_names_end_with:
      text: Service

    # SERVICES_HAVE_COMMENT rule option.
    services_have_comment:
      # Comments need to begin with the name of the thing being described. default is false.
      should_follow_golang_style: true

    # MESSAGES_HAVE_COMMENT rule option.
    messages_have_comment:
      # Comments need to begin with the name of the thing being described. default is false.
      should_follow_golang_style: false

    # RPCS_HAVE_COMMENT rule option.
    rpcs_have_comment:
      # Comments need to begin with the name of the thing being described. default is false.
      should_follow_golang_style: true

    # FIELDS_HAVE_COMMENT rule option.
    fields_have_comment:
      # Comments need to begin with the name of the thing being described. default is false.
      should_follow_golang_style: true

    # ENUMS_HAVE_COMMENT rule option.
    enums_have_comment:
      # Comments need to begin with the name of the thing being described. default is false.
      should_follow_golang_style: true

    # ENUM_FIELDS_HAVE_COMMENT rule option.
    enum_fields_have_comment:
      # Comments need to begin with the name of the thing being described. default is false.
      should_follow_golang_style: true

    # SYNTAX_CONSISTENT rule option.
    syntax_consistent:
      # Default is proto3.
      version: proto3
